config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'restaurants#index'

  resources :restaurants
end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    # user.is_admin?
    true
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord

  belongs_to :restaurant

  has_one_attached :image
  validates :image, file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }


  validates :name, presence: true, length: {
    maximum: 50
  }

  validates :price, presence: true, numericality: {
    greater_than_or_equal_to: 0
  }

  validates :desc, presence: true, length: {
    maximum: 250
  }

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :foods, dependent: :destroy

  has_one_attached :image
  validates :image, file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }

  validates :name, presence: true, length: {
    maximum: 50
  }

  validates :description, presence: true, length: {
    maximum: 250
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 50 }
  validates :phone, presence: true, numericality: true, length: { minimum: 7, maximum: 15 }
  validates :adress, presence: true, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :adress])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone, :adress])
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      &#x2630;
    </button>

    <%= link_to 'Home', root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="navbar-nav ml-auto">
        <div class="navbar-nav ml-auto">
          <% if user_signed_in? %>

            <div class="nav-item">
              <span class="navbar-text">
                Hello, &nbsp;
              <span>
            </div>

            <div class="dropdown show">
              <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </div>
            <div>
          <% else %>
            <div class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </div>
            <div class="nav-item">
              <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework68AldiyarPrimbayev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'application/navbar' %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>

  </body>
</html>

app/views/restaurants/index.html.erb
<div class="row">
  <% @restaurants.each do |restaurant| %>

    <div class="col-4 pb-3 border border-primary rounded d-flex flex-column align-items-center">
      <h2><%= link_to "#{restaurant.name}", restaurant_path(restaurant) %></h2>
      <% if restaurant.image.attached? %>
        <%= image_tag restaurant.image, size: 100 %>
      <% end %>
    </div>

  <% end %>
</div>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

<% if @restaurant.image.attached? %>
  <%= image_tag @restaurant.image, size: 100 %>
<% end %>

<p><%= @restaurant.description %></p>

<div class="row">

  <% @restaurant.foods.each do |food| %>

    <div class="col-4 border border-grey rounded d-flex flex-column align-items-center">
      <p><%= food.name %></p>

      <% if food.image.attached? %>
        <%= image_tag food.image, size: 100 %>
      <% end %>

      <p><%= food.desc %></p>
    </div>

  <% end %>

</div>